DATABASE_URL: "postgres://root:@localhost:5432/car_pool?sslmode=disable"
JWT_EXPIRATION: 43200
JWT_ISSUER_KEY: ""
JWT_REALM_NAME: ""
JWT_PRIVATE_KEY_PATH: "/secret/jwtRS256.key"
JWT_PUBLIC_KEY_PATH: "/secret/jwtRS256.key.pub"
